☐ Process duplicate deviations
✓ Merge sentences to paragraphs?
✓ Improve speed. add Async annotations
✓ Add async to all the search operations
✓ Add Log
✓ Support multiple sentence similarity algorithms
✓ Add an new sentence generation option
☐ Tag (new) documents and support download
☐ support track changes

☐ Configuration file
	database
	filepath
	async parameters

☐ Import to database
☐ Support Chinese and English (low priority)